// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pingcap/metering_sdk/writer (interfaces: MeteringWriter)
//
// Generated by this command:
//
//	mockgen -package metering github.com/pingcap/metering_sdk/writer MeteringWriter
//

// Package metering is a generated GoMock package.
package metering

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMeteringWriter is a mock of MeteringWriter interface.
type MockMeteringWriter struct {
	ctrl     *gomock.Controller
	recorder *MockMeteringWriterMockRecorder
}

// MockMeteringWriterMockRecorder is the mock recorder for MockMeteringWriter.
type MockMeteringWriterMockRecorder struct {
	mock *MockMeteringWriter
}

// NewMockMeteringWriter creates a new mock instance.
func NewMockMeteringWriter(ctrl *gomock.Controller) *MockMeteringWriter {
	mock := &MockMeteringWriter{ctrl: ctrl}
	mock.recorder = &MockMeteringWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeteringWriter) EXPECT() *MockMeteringWriterMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockMeteringWriter) ISGOMOCK() struct{} {
	return struct{}{}
}

// Close mocks base method.
func (m *MockMeteringWriter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMeteringWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMeteringWriter)(nil).Close))
}

// Write mocks base method.
func (m *MockMeteringWriter) Write(arg0 context.Context, arg1 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockMeteringWriterMockRecorder) Write(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockMeteringWriter)(nil).Write), arg0, arg1)
}
